name: Codewars Readme Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'  # Ejecutar cada 2 días a la medianoche

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.actor != 'AlexDeveloperBot'

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configura Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Instala dependencias
      working-directory: ./ 
      run: npm install

    - name: Ejecuta script
      working-directory: ./ 
      run: node generator.js

    - name: Borra node_modules
      working-directory: ./ 
      run: rm -rf node_modules

    - name: Configura Git con el bot
      run: |
        git config --global user.name "AlexDeveloperBot"
        git config --global user.email "hosting@alexdevuwu.com"

    - name: Commit y push de los cambios
      run: |
        git add .
        git commit -m "Readmes generados para los codewars"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
